### ISSUE TITLE
Ambient color values not being applied

### ISSUE THREAD

**Issue by askhuman** [arocks/puray#4]
Thanks for sharing this nice implementation.

There is a small bug in `engine.py` on line 72:
`color = material.ambient * Color.from_hex("#000000")`
Color is being set to black i.e. 0, so ambient values are never applied. Should be `Color.from_hex("#ffffff")` or `Color(0, 0, 0)`

**Comment by arocks** [comment]
Agree... I plan to mention this in the next part. Thanks! ☺

**Comment by askhuman** [comment]
Sorry, I meant `Color(1, 1, 1)` not `Color(0, 0, 0)` - but I'm sure you got the idea.
